import { randomUUID } from 'crypto'
import { mkdirSync } from 'fs'
import { basename, join } from 'path'

const GENERATED_MEDIA_DIRECTORY = 'media'
const SAFE_PATH_SEGMENT = /[^a-zA-Z0-9._-]/g

export interface ManagedMediaPathOptions {
  userDataPath: string
  operation: 'silence-trim' | 'clip-editor' | 'smart-split'
  fileName: string
  runId?: string
}

function sanitizePathSegment(value: string, fallback: string): string {
  const sanitized = value.replace(SAFE_PATH_SEGMENT, '_').replace(/^\.+/, '')
  return sanitized.length > 0 ? sanitized : fallback
}

export function getManagedMediaDirectory(userDataPath: string): string {
  return join(userDataPath, GENERATED_MEDIA_DIRECTORY)
}

/**
 * Allocates a durable, collision-free path for media generated by BatchEdit.
 * A caller-provided run ID keeps related outputs together and makes tests deterministic.
 */
export function createManagedMediaPath({
  userDataPath,
  operation,
  fileName,
  runId = randomUUID()
}: ManagedMediaPathOptions): string {
  const safeRunId = sanitizePathSegment(runId, 'generated-run')
  const safeFileName = sanitizePathSegment(basename(fileName), 'generated.mp4')
  const outputDirectory = join(getManagedMediaDirectory(userDataPath), operation, safeRunId)
  mkdirSync(outputDirectory, { recursive: true })
  return join(outputDirectory, safeFileName)
}
